import { secretApiRoutes } from "./secret/routes.ts";
export { secretApiRoutes, type SecretApiRoute } from "./secret/routes.ts";
import { serviceAccountApiRoutes } from "./service-account/routes.ts";
export { serviceAccountApiRoutes, type ServiceAccountApiRoute } from "./service-account/routes.ts";
import { namespaceApiRoutes } from "./namespace/routes.ts";
export { namespaceApiRoutes, type NamespaceApiRoute } from "./namespace/routes.ts";
import { agentApiRoutes } from "./agent/routes.ts";
export { agentApiRoutes, type AgentApiRoute } from "./agent/routes.ts";
import { lifecycleApiRoutes } from "./agent/lifecycle-routes.ts";
export { lifecycleApiRoutes, type LifecycleApiRoute } from "./agent/lifecycle-routes.ts";
import { configurationApiRoutes } from "./configuration/routes.ts";
export { configurationApiRoutes, type ConfigurationApiRoute } from "./configuration/routes.ts";
import {
  ChannelBindingListQuery,
  ChannelInstallationParams,
  ChannelHumanBindingParams,
  ChannelAgentBindingParams,
  CreateChannelInstallationBody,
  CreateChannelHumanBindingBody,
  CreateChannelAgentBindingBody,
  ChangeChannelBindingStatusBody,
  ChannelInstallationResponse,
  ChannelInstallationListResponse,
  ChannelHumanBindingResponse,
  ChannelHumanBindingListResponse,
  ChannelAgentBindingResponse,
  ChannelAgentBindingListResponse,
} from "./channel-bindings.ts";
import { Type } from "typebox";

import {
  AgentParams,
  EmptyQuery,
  NamedResourceBody,
  NamespaceParams,
  UpdateWorkspaceFileBody,
  WorkspaceFileParams,
} from "./common.ts";
import {
  InstallationResponse,
  ProviderListResponse,
  WorkspaceFileResponse,
  WorkspaceFileUpdateResponse,
} from "./resources.ts";

const ErrorResponseRef = Type.Ref("ErrorResponse");

const readErrors = {
  400: ErrorResponseRef,
  401: ErrorResponseRef,
  403: ErrorResponseRef,
  404: ErrorResponseRef,
  500: ErrorResponseRef,
  503: ErrorResponseRef,
} as const;

const createErrors = {
  ...readErrors,
  409: ErrorResponseRef,
  413: ErrorResponseRef,
  415: ErrorResponseRef,
} as const;

const mutationErrors = {
  ...readErrors,
  409: ErrorResponseRef,
} as const;

export const occApiRoutes = [
  {
    operationId: "createChannelInstallation",
    method: "POST",
    path: "/api/channel-installations",
    action: "openclaw.channel_bindings.createChannelInstallation",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Create channel app installation metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      body: CreateChannelInstallationBody,
      response: { 201: ChannelInstallationResponse, ...createErrors },
    },
  },
  {
    operationId: "listChannelInstallations",
    method: "GET",
    path: "/api/channel-installations",
    action: "openclaw.channel_bindings.listChannelInstallations",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List channel app installation metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: ChannelBindingListQuery,
      response: { 200: ChannelInstallationListResponse, ...readErrors },
    },
  },
  {
    operationId: "getChannelInstallation",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId",
    action: "openclaw.channel_bindings.getChannelInstallation",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get channel app installation metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelInstallationParams,
      response: { 200: ChannelInstallationResponse, ...readErrors },
    },
  },
  {
    operationId: "setChannelInstallationStatus",
    method: "PATCH",
    path: "/api/channel-installations/:channelInstallationId",
    action: "openclaw.channel_bindings.setChannelInstallationStatus",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Set channel app installation status",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelInstallationParams,
      body: ChangeChannelBindingStatusBody,
      response: { 200: ChannelInstallationResponse, ...createErrors },
    },
  },
  {
    operationId: "createChannelHumanBinding",
    method: "POST",
    path: "/api/channel-installations/:channelInstallationId/human-bindings",
    action: "openclaw.channel_bindings.createChannelHumanBinding",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Create channel human binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelInstallationParams,
      body: CreateChannelHumanBindingBody,
      response: { 201: ChannelHumanBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "listChannelHumanBindings",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId/human-bindings",
    action: "openclaw.channel_bindings.listChannelHumanBindings",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List channel human binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: ChannelBindingListQuery,
      params: ChannelInstallationParams,
      response: { 200: ChannelHumanBindingListResponse, ...readErrors },
    },
  },
  {
    operationId: "getChannelHumanBinding",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId/human-bindings/:bindingId",
    action: "openclaw.channel_bindings.getChannelHumanBinding",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get channel human binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelHumanBindingParams,
      response: { 200: ChannelHumanBindingResponse, ...readErrors },
    },
  },
  {
    operationId: "setChannelHumanBindingStatus",
    method: "PATCH",
    path: "/api/channel-installations/:channelInstallationId/human-bindings/:bindingId",
    action: "openclaw.channel_bindings.setChannelHumanBindingStatus",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Set channel human binding status",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelHumanBindingParams,
      body: ChangeChannelBindingStatusBody,
      response: { 200: ChannelHumanBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "createChannelAgentBinding",
    method: "POST",
    path: "/api/channel-installations/:channelInstallationId/agent-bindings",
    action: "openclaw.channel_bindings.createChannelAgentBinding",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Create channel Agent binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelInstallationParams,
      body: CreateChannelAgentBindingBody,
      response: { 201: ChannelAgentBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "listChannelAgentBindings",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId/agent-bindings",
    action: "openclaw.channel_bindings.listChannelAgentBindings",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List channel Agent binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: ChannelBindingListQuery,
      params: ChannelInstallationParams,
      response: { 200: ChannelAgentBindingListResponse, ...readErrors },
    },
  },
  {
    operationId: "getChannelAgentBinding",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId/agent-bindings/:bindingId",
    action: "openclaw.channel_bindings.getChannelAgentBinding",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get channel Agent binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelAgentBindingParams,
      response: { 200: ChannelAgentBindingResponse, ...readErrors },
    },
  },
  {
    operationId: "setChannelAgentBindingStatus",
    method: "PATCH",
    path: "/api/channel-installations/:channelInstallationId/agent-bindings/:bindingId",
    action: "openclaw.channel_bindings.setChannelAgentBindingStatus",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Set channel Agent binding status",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelAgentBindingParams,
      body: ChangeChannelBindingStatusBody,
      response: { 200: ChannelAgentBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "bootstrapInstallation",
    method: "POST",
    path: "/installation/bootstrap",
    action: "openclaw.installation.bootstrap",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Bootstrap the singleton Installation",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      body: NamedResourceBody,
      response: {
        201: InstallationResponse,
        400: ErrorResponseRef,
        401: ErrorResponseRef,
        403: ErrorResponseRef,
        409: ErrorResponseRef,
        413: ErrorResponseRef,
        415: ErrorResponseRef,
        500: ErrorResponseRef,
        503: ErrorResponseRef,
      },
    },
  },
  {
    operationId: "getInstallation",
    method: "GET",
    path: "/installation",
    action: "openclaw.installation.read",
    iamAction: "read",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get the singleton Installation",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: InstallationResponse, ...readErrors },
    },
  },
  {
    operationId: "listProviders",
    method: "GET",
    path: "/providers",
    action: "openclaw.providers.list",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List configured Providers",
    tags: ["Providers"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: ProviderListResponse, ...readErrors },
    },
  },
  ...namespaceApiRoutes,
  ...configurationApiRoutes,
  ...secretApiRoutes,
  ...serviceAccountApiRoutes,
  agentApiRoutes[0],
  agentApiRoutes[1],
  agentApiRoutes[2],
  agentApiRoutes[3],
  agentApiRoutes[4],
  {
    operationId: "getAgentWorkspaceFile",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/workspace/files/:name",
    action: "openclaw.agents.workspace.files.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Read an allowed workspace file from one active Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: WorkspaceFileParams,
      response: { 200: WorkspaceFileResponse, ...readErrors },
    },
  },
  {
    operationId: "putAgentWorkspaceFile",
    method: "PUT",
    path: "/namespaces/:namespaceId/agents/:agentId/workspace/files/:name",
    action: "openclaw.agents.workspace.files.write",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Create or replace an allowed workspace file for one active Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: WorkspaceFileParams,
      body: UpdateWorkspaceFileBody,
      response: { 200: WorkspaceFileUpdateResponse, ...createErrors },
    },
  },
  agentApiRoutes[5],
  agentApiRoutes[6],
  ...lifecycleApiRoutes,
] as const;

export type OccApiRoute = (typeof occApiRoutes)[number];
export type OccApiOperationId = OccApiRoute["operationId"];
