import { configurationApiRoutes } from "./configuration/routes.ts";
export { configurationApiRoutes, type ConfigurationApiRoute } from "./configuration/routes.ts";
import {
  ChannelBindingListQuery,
  ChannelInstallationParams,
  ChannelHumanBindingParams,
  ChannelAgentBindingParams,
  CreateChannelInstallationBody,
  CreateChannelHumanBindingBody,
  CreateChannelAgentBindingBody,
  ChangeChannelBindingStatusBody,
  ChannelInstallationResponse,
  ChannelInstallationListResponse,
  ChannelHumanBindingResponse,
  ChannelHumanBindingListResponse,
  ChannelAgentBindingResponse,
  ChannelAgentBindingListResponse,
} from "./channel-bindings.ts";
import { Type } from "typebox";

import {
  AgentParams,
  CreateAgentBody,
  CreateNamespaceBody,
  CreateSecretBody,
  CreateServiceAccountBody,
  CreateServiceAccountCredentialBody,
  EmptyQuery,
  NamedResourceBody,
  NamespaceParams,
  RevisionParams,
  SecretParams,
  ServiceAccountParams,
  UpdateAgentBody,
  UpdateSecretBody,
  UpdateServiceAccountCredentialBody,
  UpdateWorkspaceFileBody,
  WorkspaceFileParams,
} from "./common.ts";
import {
  AgentListResponse,
  AgentResponse,
  AgentRevisionListResponse,
  AgentRevisionResponse,
  InstallationResponse,
  NamespaceListResponse,
  NamespaceResponse,
  ProviderListResponse,
  ServiceAccountListResponse,
  ServiceAccountResponse,
  WorkspaceFileResponse,
  WorkspaceFileUpdateResponse,
} from "./resources.ts";

const ErrorResponseRef = Type.Ref("ErrorResponse");
const SecretResponseRef = Type.Ref("SecretResponse");

const readErrors = {
  400: ErrorResponseRef,
  401: ErrorResponseRef,
  403: ErrorResponseRef,
  404: ErrorResponseRef,
  500: ErrorResponseRef,
  503: ErrorResponseRef,
} as const;

const createErrors = {
  ...readErrors,
  409: ErrorResponseRef,
  413: ErrorResponseRef,
  415: ErrorResponseRef,
} as const;

const mutationErrors = {
  ...readErrors,
  409: ErrorResponseRef,
} as const;

export const occApiRoutes = [
  {
    operationId: "createChannelInstallation",
    method: "POST",
    path: "/api/channel-installations",
    action: "openclaw.channel_bindings.createChannelInstallation",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Create channel app installation metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      body: CreateChannelInstallationBody,
      response: { 201: ChannelInstallationResponse, ...createErrors },
    },
  },
  {
    operationId: "listChannelInstallations",
    method: "GET",
    path: "/api/channel-installations",
    action: "openclaw.channel_bindings.listChannelInstallations",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List channel app installation metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: ChannelBindingListQuery,
      response: { 200: ChannelInstallationListResponse, ...readErrors },
    },
  },
  {
    operationId: "getChannelInstallation",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId",
    action: "openclaw.channel_bindings.getChannelInstallation",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get channel app installation metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelInstallationParams,
      response: { 200: ChannelInstallationResponse, ...readErrors },
    },
  },
  {
    operationId: "setChannelInstallationStatus",
    method: "PATCH",
    path: "/api/channel-installations/:channelInstallationId",
    action: "openclaw.channel_bindings.setChannelInstallationStatus",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Set channel app installation status",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelInstallationParams,
      body: ChangeChannelBindingStatusBody,
      response: { 200: ChannelInstallationResponse, ...createErrors },
    },
  },
  {
    operationId: "createChannelHumanBinding",
    method: "POST",
    path: "/api/channel-installations/:channelInstallationId/human-bindings",
    action: "openclaw.channel_bindings.createChannelHumanBinding",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Create channel human binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelInstallationParams,
      body: CreateChannelHumanBindingBody,
      response: { 201: ChannelHumanBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "listChannelHumanBindings",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId/human-bindings",
    action: "openclaw.channel_bindings.listChannelHumanBindings",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List channel human binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: ChannelBindingListQuery,
      params: ChannelInstallationParams,
      response: { 200: ChannelHumanBindingListResponse, ...readErrors },
    },
  },
  {
    operationId: "getChannelHumanBinding",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId/human-bindings/:bindingId",
    action: "openclaw.channel_bindings.getChannelHumanBinding",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get channel human binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelHumanBindingParams,
      response: { 200: ChannelHumanBindingResponse, ...readErrors },
    },
  },
  {
    operationId: "setChannelHumanBindingStatus",
    method: "PATCH",
    path: "/api/channel-installations/:channelInstallationId/human-bindings/:bindingId",
    action: "openclaw.channel_bindings.setChannelHumanBindingStatus",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Set channel human binding status",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelHumanBindingParams,
      body: ChangeChannelBindingStatusBody,
      response: { 200: ChannelHumanBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "createChannelAgentBinding",
    method: "POST",
    path: "/api/channel-installations/:channelInstallationId/agent-bindings",
    action: "openclaw.channel_bindings.createChannelAgentBinding",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Create channel Agent binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelInstallationParams,
      body: CreateChannelAgentBindingBody,
      response: { 201: ChannelAgentBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "listChannelAgentBindings",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId/agent-bindings",
    action: "openclaw.channel_bindings.listChannelAgentBindings",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List channel Agent binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: ChannelBindingListQuery,
      params: ChannelInstallationParams,
      response: { 200: ChannelAgentBindingListResponse, ...readErrors },
    },
  },
  {
    operationId: "getChannelAgentBinding",
    method: "GET",
    path: "/api/channel-installations/:channelInstallationId/agent-bindings/:bindingId",
    action: "openclaw.channel_bindings.getChannelAgentBinding",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get channel Agent binding metadata",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelAgentBindingParams,
      response: { 200: ChannelAgentBindingResponse, ...readErrors },
    },
  },
  {
    operationId: "setChannelAgentBindingStatus",
    method: "PATCH",
    path: "/api/channel-installations/:channelInstallationId/agent-bindings/:bindingId",
    action: "openclaw.channel_bindings.setChannelAgentBindingStatus",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Set channel Agent binding status",
    tags: ["Channel bindings"],
    schema: {
      querystring: EmptyQuery,
      params: ChannelAgentBindingParams,
      body: ChangeChannelBindingStatusBody,
      response: { 200: ChannelAgentBindingResponse, ...createErrors },
    },
  },
  {
    operationId: "bootstrapInstallation",
    method: "POST",
    path: "/installation/bootstrap",
    action: "openclaw.installation.bootstrap",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Bootstrap the singleton Installation",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      body: NamedResourceBody,
      response: {
        201: InstallationResponse,
        400: ErrorResponseRef,
        401: ErrorResponseRef,
        403: ErrorResponseRef,
        409: ErrorResponseRef,
        413: ErrorResponseRef,
        415: ErrorResponseRef,
        500: ErrorResponseRef,
        503: ErrorResponseRef,
      },
    },
  },
  {
    operationId: "getInstallation",
    method: "GET",
    path: "/installation",
    action: "openclaw.installation.read",
    iamAction: "read",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "Get the singleton Installation",
    tags: ["Installation"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: InstallationResponse, ...readErrors },
    },
  },
  {
    operationId: "listProviders",
    method: "GET",
    path: "/providers",
    action: "openclaw.providers.list",
    iamAction: "administer",
    resourceKind: "installation",
    authorizationTarget: "installation",
    summary: "List configured Providers",
    tags: ["Providers"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: ProviderListResponse, ...readErrors },
    },
  },
  {
    operationId: "createNamespace",
    method: "POST",
    path: "/namespaces",
    action: "openclaw.namespaces.create",
    iamAction: "create",
    resourceKind: "namespace",
    authorizationTarget: "installation_collection",
    summary: "Create an Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      body: CreateNamespaceBody,
      response: { 201: NamespaceResponse, ...createErrors },
    },
  },
  {
    operationId: "listNamespaces",
    method: "GET",
    path: "/namespaces",
    action: "openclaw.namespaces.list",
    iamAction: "read",
    resourceKind: "namespace",
    authorizationTarget: "namespace_candidates",
    summary: "List authorized Namespaces",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      response: { 200: NamespaceListResponse, ...readErrors },
    },
  },
  {
    operationId: "getNamespace",
    method: "GET",
    path: "/namespaces/:namespaceId",
    action: "openclaw.namespaces.read",
    iamAction: "read",
    resourceKind: "namespace",
    authorizationTarget: "namespace",
    summary: "Get an exact Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: NamespaceResponse, ...readErrors },
    },
  },
  {
    operationId: "deleteNamespace",
    method: "DELETE",
    path: "/namespaces/:namespaceId",
    action: "openclaw.namespaces.delete",
    iamAction: "delete",
    resourceKind: "namespace",
    authorizationTarget: "namespace",
    summary: "Begin deletion of an empty Installation-owned Namespace",
    tags: ["Namespaces"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 202: NamespaceResponse, ...mutationErrors },
    },
  },
  ...configurationApiRoutes,
  {
    operationId: "createSecret",
    method: "POST",
    path: "/namespaces/:namespaceId/secrets",
    action: "openclaw.secrets.create",
    iamAction: "create",
    resourceKind: "secret",
    authorizationTarget: "namespace_collection",
    summary: "Create exact Namespace-owned Secret material and return metadata only",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateSecretBody,
      response: { 201: SecretResponseRef, ...createErrors },
    },
  },
  {
    operationId: "getSecret",
    method: "GET",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.read",
    iamAction: "read",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Get exact Namespace-owned Secret metadata without revealing material",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      response: { 200: SecretResponseRef, ...readErrors },
    },
  },
  {
    operationId: "updateSecret",
    method: "PATCH",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.update",
    iamAction: "update",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Replace exact Namespace-owned Secret material and return stable metadata",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      body: UpdateSecretBody,
      response: { 200: SecretResponseRef, ...createErrors },
    },
  },
  {
    operationId: "deleteSecret",
    method: "DELETE",
    path: "/namespaces/:namespaceId/secrets/:secretId",
    action: "openclaw.secrets.delete",
    iamAction: "delete",
    resourceKind: "secret",
    authorizationTarget: "secret",
    summary: "Delete exact unbound Namespace-owned Secret material",
    tags: ["Secrets"],
    schema: {
      querystring: EmptyQuery,
      params: SecretParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "createServiceAccount",
    method: "POST",
    path: "/namespaces/:namespaceId/service-accounts",
    action: "openclaw.service_accounts.create",
    iamAction: "create",
    resourceKind: "service_account",
    authorizationTarget: "namespace_collection",
    summary: "Create a native Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateServiceAccountBody,
      response: { 201: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "listServiceAccounts",
    method: "GET",
    path: "/namespaces/:namespaceId/service-accounts",
    action: "openclaw.service_accounts.list",
    iamAction: "read",
    resourceKind: "service_account",
    authorizationTarget: "namespace_and_service_account_candidates",
    summary: "List authorized Namespace-owned ServiceAccounts in one exact Namespace",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: ServiceAccountListResponse, ...readErrors },
    },
  },
  {
    operationId: "getServiceAccount",
    method: "GET",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId",
    action: "openclaw.service_accounts.read",
    iamAction: "read",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Get an exact Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      response: { 200: ServiceAccountResponse, ...readErrors },
    },
  },
  {
    operationId: "createServiceAccountCredential",
    method: "POST",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId/credentials",
    action: "openclaw.service_accounts.credentials.create",
    iamAction: "update",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Issue a managed credential for an exact Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      body: CreateServiceAccountCredentialBody,
      response: { 201: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "updateServiceAccountCredential",
    method: "PATCH",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId/credential",
    action: "openclaw.service_accounts.update",
    iamAction: "update",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Associate an exact Namespace-local credential reference with a ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      body: UpdateServiceAccountCredentialBody,
      response: { 200: ServiceAccountResponse, ...createErrors },
    },
  },
  {
    operationId: "deleteServiceAccount",
    method: "DELETE",
    path: "/namespaces/:namespaceId/service-accounts/:serviceAccountId",
    action: "openclaw.service_accounts.delete",
    iamAction: "delete",
    resourceKind: "service_account",
    authorizationTarget: "service_account",
    summary: "Delete an exact unreferenced Namespace-owned ServiceAccount",
    tags: ["Service accounts"],
    schema: {
      querystring: EmptyQuery,
      params: ServiceAccountParams,
      response: { 204: Type.Null(), ...mutationErrors },
    },
  },
  {
    operationId: "createAgent",
    method: "POST",
    path: "/namespaces/:namespaceId/agents",
    action: "openclaw.agents.create",
    iamAction: "create",
    resourceKind: "agent",
    authorizationTarget: "namespace_collection",
    summary: "Create a Namespace-owned Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      body: CreateAgentBody,
      response: { 201: AgentResponse, ...createErrors },
    },
  },
  {
    operationId: "updateAgent",
    method: "PATCH",
    path: "/namespaces/:namespaceId/agents/:agentId",
    action: "openclaw.agents.update",
    iamAction: "update",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Replace an exact Namespace-owned Agent's editable draft",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      body: UpdateAgentBody,
      response: { 200: AgentResponse, ...createErrors },
    },
  },
  {
    operationId: "listAgents",
    method: "GET",
    path: "/namespaces/:namespaceId/agents",
    action: "openclaw.agents.list",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "namespace_and_agent_candidates",
    summary: "List authorized Agents in one exact Namespace",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: NamespaceParams,
      response: { 200: AgentListResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgent",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId",
    action: "openclaw.agents.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Get an exact Namespace-owned Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentResponse, ...readErrors },
    },
  },
  {
    operationId: "deployAgent",
    method: "POST",
    path: "/namespaces/:namespaceId/agents/:agentId/deploy",
    action: "openclaw.agents.deploy",
    iamAction: "deploy",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Admit an immutable revision from the Agent's saved draft",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 202: AgentRevisionResponse, ...mutationErrors },
    },
  },
  {
    operationId: "getAgentWorkspaceFile",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/workspace/files/:name",
    action: "openclaw.agents.workspace.files.read",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Read an allowed workspace file from one active Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: WorkspaceFileParams,
      response: { 200: WorkspaceFileResponse, ...readErrors },
    },
  },
  {
    operationId: "putAgentWorkspaceFile",
    method: "PUT",
    path: "/namespaces/:namespaceId/agents/:agentId/workspace/files/:name",
    action: "openclaw.agents.workspace.files.write",
    iamAction: "operate",
    resourceKind: "agent",
    authorizationTarget: "agent",
    summary: "Create or replace an allowed workspace file for one active Agent",
    tags: ["Agents"],
    schema: {
      querystring: EmptyQuery,
      params: WorkspaceFileParams,
      body: UpdateWorkspaceFileBody,
      response: { 200: WorkspaceFileUpdateResponse, ...createErrors },
    },
  },
  {
    operationId: "listAgentRevisions",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/revisions",
    action: "openclaw.agent_revisions.list",
    iamAction: "read",
    resourceKind: "agent",
    authorizationTarget: "agent_collection",
    summary: "List authorized immutable revisions for one exact Agent",
    tags: ["Agent revisions"],
    schema: {
      querystring: EmptyQuery,
      params: AgentParams,
      response: { 200: AgentRevisionListResponse, ...readErrors },
    },
  },
  {
    operationId: "getAgentRevision",
    method: "GET",
    path: "/namespaces/:namespaceId/agents/:agentId/revisions/:revisionId",
    action: "openclaw.agent_revisions.read",
    iamAction: "read",
    resourceKind: "agent_revision",
    authorizationTarget: "requested_revision",
    summary: "Get an exact authorized immutable Agent revision",
    tags: ["Agent revisions"],
    schema: {
      querystring: EmptyQuery,
      params: RevisionParams,
      response: { 200: AgentRevisionResponse, ...readErrors },
    },
  },
] as const;

export type OccApiRoute = (typeof occApiRoutes)[number];
export type OccApiOperationId = OccApiRoute["operationId"];
