// Generated by scripts/generate-credential-schema-manifest.mjs; excludes this manifest.
export const CORE_SCHEMA_PRIMITIVE_MANIFEST_V1 = [
  {
    kind: "schema-interpreter",
    name: "oce-closed-schema-interpreter",
    version: 1,
    files: [
      {
        path: "packages/occ/src/credential-broker-v1/schema-admission.ts",
        sha256: "14a85d3b4e4c352112e4a2ca778ca3e9e90a3ddad56a8ae3df31991d47723527",
      },
      {
        path: "packages/occ/src/credential-broker-v1/schema-json.ts",
        sha256: "925345e38bdabfc1d8b3b85f6ef5109c3c9f1d003a092a3957365bf268a4239b",
      },
      {
        path: "packages/occ/src/credential-broker-v1/schema-primitives.ts",
        sha256: "57403e185390cabc01e3ff7c4da5f7cf06a923c4072629390fba0819d3fe2d39",
      },
      {
        path: "packages/occ/src/credential-gateway-v1/schema.ts",
        sha256: "008934c192ab5e0603334a77cceb4e74921449c19d47948587531debf6fa44d2",
      },
    ],
    dependencies: { ajv: "8.20.0" },
    digest: "sha256:020c3470abd81ff7c490b7b5941effa1cd623afaa34f356c7a4b0e7807010af4",
  },
  {
    kind: "canonicalization",
    name: "oce-json-canonical",
    version: 1,
    files: [
      {
        path: "packages/occ/src/credential-broker-v1/schema-admission.ts",
        sha256: "14a85d3b4e4c352112e4a2ca778ca3e9e90a3ddad56a8ae3df31991d47723527",
      },
      {
        path: "packages/occ/src/credential-broker-v1/schema-json.ts",
        sha256: "925345e38bdabfc1d8b3b85f6ef5109c3c9f1d003a092a3957365bf268a4239b",
      },
      {
        path: "packages/occ/src/credential-broker-v1/schema-primitives.ts",
        sha256: "57403e185390cabc01e3ff7c4da5f7cf06a923c4072629390fba0819d3fe2d39",
      },
      {
        path: "packages/occ/src/credential-gateway-v1/schema.ts",
        sha256: "008934c192ab5e0603334a77cceb4e74921449c19d47948587531debf6fa44d2",
      },
    ],
    dependencies: { ajv: "8.20.0" },
    digest: "sha256:0095ebe47876e58c0475bbf221580e11d6072f78ea075c8f73f3c0c2c6f8406a",
  },
] as const;
