// Generated by scripts/generate-credential-schema-manifest.mjs; excludes this manifest.
export const CORE_SCHEMA_PRIMITIVE_MANIFEST_V1 = [
  {
    kind: "schema-interpreter",
    name: "oce-closed-schema-interpreter",
    version: 1,
    files: [
      {
        path: "packages/occ/src/credential-broker-v1/schema-admission.ts",
        sha256: "d55035a6f0e288b39689fa7d11473a5725dc0db9fa65f97d1b07894141658201",
      },
      {
        path: "packages/occ/src/credential-broker-v1/schema-json.ts",
        sha256: "925345e38bdabfc1d8b3b85f6ef5109c3c9f1d003a092a3957365bf268a4239b",
      },
      {
        path: "packages/occ/src/credential-broker-v1/schema-primitives.ts",
        sha256: "57403e185390cabc01e3ff7c4da5f7cf06a923c4072629390fba0819d3fe2d39",
      },
      {
        path: "packages/occ/src/credential-gateway-v1/schema.ts",
        sha256: "008934c192ab5e0603334a77cceb4e74921449c19d47948587531debf6fa44d2",
      },
    ],
    dependencies: { ajv: "8.20.0" },
    digest: "sha256:9ffa09e603aa793b87ce445ba14ac5721c483b20dc62c149381109ee7aacce64",
  },
  {
    kind: "canonicalization",
    name: "oce-json-canonical",
    version: 1,
    files: [
      {
        path: "packages/occ/src/credential-broker-v1/schema-admission.ts",
        sha256: "d55035a6f0e288b39689fa7d11473a5725dc0db9fa65f97d1b07894141658201",
      },
      {
        path: "packages/occ/src/credential-broker-v1/schema-json.ts",
        sha256: "925345e38bdabfc1d8b3b85f6ef5109c3c9f1d003a092a3957365bf268a4239b",
      },
      {
        path: "packages/occ/src/credential-broker-v1/schema-primitives.ts",
        sha256: "57403e185390cabc01e3ff7c4da5f7cf06a923c4072629390fba0819d3fe2d39",
      },
      {
        path: "packages/occ/src/credential-gateway-v1/schema.ts",
        sha256: "008934c192ab5e0603334a77cceb4e74921449c19d47948587531debf6fa44d2",
      },
    ],
    dependencies: { ajv: "8.20.0" },
    digest: "sha256:7738ed829a459a3141d7393487bd4f1ff6144cc2daa8620f9ab2b640fd707724",
  },
] as const;
