// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// OpenShell v0.0.113 / v0.0.116 lifecycle wire schema used by OpenClaw Enterprise.
//
// This intentionally models only the messages needed for
// Sandbox creation, lookup, and deletion. Field numbers match the
// public openshell.proto, datamodel.proto, and sandbox.proto at upstream commit
// 455883905a7ace88e6e69834dc0685bfc799ad44. Reachable launch fields are complete;
// local nested type names are wire-equivalent to the upstream packages.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: openshell.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceStatus int32

const (
	ServiceStatus_SERVICE_STATUS_UNSPECIFIED ServiceStatus = 0
	ServiceStatus_SERVICE_STATUS_HEALTHY     ServiceStatus = 1
	ServiceStatus_SERVICE_STATUS_DEGRADED    ServiceStatus = 2
	ServiceStatus_SERVICE_STATUS_UNHEALTHY   ServiceStatus = 3
)

// Enum value maps for ServiceStatus.
var (
	ServiceStatus_name = map[int32]string{
		0: "SERVICE_STATUS_UNSPECIFIED",
		1: "SERVICE_STATUS_HEALTHY",
		2: "SERVICE_STATUS_DEGRADED",
		3: "SERVICE_STATUS_UNHEALTHY",
	}
	ServiceStatus_value = map[string]int32{
		"SERVICE_STATUS_UNSPECIFIED": 0,
		"SERVICE_STATUS_HEALTHY":     1,
		"SERVICE_STATUS_DEGRADED":    2,
		"SERVICE_STATUS_UNHEALTHY":   3,
	}
)

func (x ServiceStatus) Enum() *ServiceStatus {
	p := new(ServiceStatus)
	*p = x
	return p
}

func (x ServiceStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_openshell_proto_enumTypes[0].Descriptor()
}

func (ServiceStatus) Type() protoreflect.EnumType {
	return &file_openshell_proto_enumTypes[0]
}

func (x ServiceStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceStatus.Descriptor instead.
func (ServiceStatus) EnumDescriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{0}
}

type SandboxPhase int32

const (
	SandboxPhase_SANDBOX_PHASE_UNSPECIFIED  SandboxPhase = 0
	SandboxPhase_SANDBOX_PHASE_PROVISIONING SandboxPhase = 1
	SandboxPhase_SANDBOX_PHASE_READY        SandboxPhase = 2
	SandboxPhase_SANDBOX_PHASE_ERROR        SandboxPhase = 3
	SandboxPhase_SANDBOX_PHASE_DELETING     SandboxPhase = 4
	SandboxPhase_SANDBOX_PHASE_UNKNOWN      SandboxPhase = 5
	SandboxPhase_SANDBOX_PHASE_STOPPING     SandboxPhase = 6
	SandboxPhase_SANDBOX_PHASE_STOPPED      SandboxPhase = 7
	SandboxPhase_SANDBOX_PHASE_STARTING     SandboxPhase = 8
)

// Enum value maps for SandboxPhase.
var (
	SandboxPhase_name = map[int32]string{
		0: "SANDBOX_PHASE_UNSPECIFIED",
		1: "SANDBOX_PHASE_PROVISIONING",
		2: "SANDBOX_PHASE_READY",
		3: "SANDBOX_PHASE_ERROR",
		4: "SANDBOX_PHASE_DELETING",
		5: "SANDBOX_PHASE_UNKNOWN",
		6: "SANDBOX_PHASE_STOPPING",
		7: "SANDBOX_PHASE_STOPPED",
		8: "SANDBOX_PHASE_STARTING",
	}
	SandboxPhase_value = map[string]int32{
		"SANDBOX_PHASE_UNSPECIFIED":  0,
		"SANDBOX_PHASE_PROVISIONING": 1,
		"SANDBOX_PHASE_READY":        2,
		"SANDBOX_PHASE_ERROR":        3,
		"SANDBOX_PHASE_DELETING":     4,
		"SANDBOX_PHASE_UNKNOWN":      5,
		"SANDBOX_PHASE_STOPPING":     6,
		"SANDBOX_PHASE_STOPPED":      7,
		"SANDBOX_PHASE_STARTING":     8,
	}
)

func (x SandboxPhase) Enum() *SandboxPhase {
	p := new(SandboxPhase)
	*p = x
	return p
}

func (x SandboxPhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SandboxPhase) Descriptor() protoreflect.EnumDescriptor {
	return file_openshell_proto_enumTypes[1].Descriptor()
}

func (SandboxPhase) Type() protoreflect.EnumType {
	return &file_openshell_proto_enumTypes[1]
}

func (x SandboxPhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SandboxPhase.Descriptor instead.
func (SandboxPhase) EnumDescriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{1}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_openshell_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        ServiceStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=openshell.v1.ServiceStatus" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_openshell_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetStatus() ServiceStatus {
	if x != nil {
		return x.Status
	}
	return ServiceStatus_SERVICE_STATUS_UNSPECIFIED
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type ObjectMeta struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Id                  string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAtMs         int64                  `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	Labels              map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceVersion     uint64                 `protobuf:"varint,5,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Annotations         map[string]string      `protobuf:"bytes,6,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workspace           string                 `protobuf:"bytes,7,opt,name=workspace,proto3" json:"workspace,omitempty"`
	DeletionTimestampMs int64                  `protobuf:"varint,8,opt,name=deletion_timestamp_ms,json=deletionTimestampMs,proto3" json:"deletion_timestamp_ms,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_openshell_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{2}
}

func (x *ObjectMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetResourceVersion() uint64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

func (x *ObjectMeta) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *ObjectMeta) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

func (x *ObjectMeta) GetDeletionTimestampMs() int64 {
	if x != nil {
		return x.DeletionTimestampMs
	}
	return 0
}

type Sandbox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *ObjectMeta            `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Spec          *SandboxSpec           `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Status        *SandboxStatus         `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Sandbox) Reset() {
	*x = Sandbox{}
	mi := &file_openshell_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sandbox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sandbox) ProtoMessage() {}

func (x *Sandbox) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sandbox.ProtoReflect.Descriptor instead.
func (*Sandbox) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{3}
}

func (x *Sandbox) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Sandbox) GetSpec() *SandboxSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Sandbox) GetStatus() *SandboxStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type SandboxSpec struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	LogLevel             string                 `protobuf:"bytes,1,opt,name=log_level,json=logLevel,proto3" json:"log_level,omitempty"`
	Environment          map[string]string      `protobuf:"bytes,5,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Template             *SandboxTemplate       `protobuf:"bytes,6,opt,name=template,proto3" json:"template,omitempty"`
	Policy               *SandboxPolicy         `protobuf:"bytes,7,opt,name=policy,proto3" json:"policy,omitempty"`
	Providers            []string               `protobuf:"bytes,8,rep,name=providers,proto3" json:"providers,omitempty"`
	ResourceRequirements *ResourceRequirements  `protobuf:"bytes,9,opt,name=resource_requirements,json=resourceRequirements,proto3" json:"resource_requirements,omitempty"`
	Command              []string               `protobuf:"bytes,12,rep,name=command,proto3" json:"command,omitempty"`
	Tty                  bool                   `protobuf:"varint,13,opt,name=tty,proto3" json:"tty,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SandboxSpec) Reset() {
	*x = SandboxSpec{}
	mi := &file_openshell_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxSpec) ProtoMessage() {}

func (x *SandboxSpec) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxSpec.ProtoReflect.Descriptor instead.
func (*SandboxSpec) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{4}
}

func (x *SandboxSpec) GetLogLevel() string {
	if x != nil {
		return x.LogLevel
	}
	return ""
}

func (x *SandboxSpec) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *SandboxSpec) GetTemplate() *SandboxTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

func (x *SandboxSpec) GetPolicy() *SandboxPolicy {
	if x != nil {
		return x.Policy
	}
	return nil
}

func (x *SandboxSpec) GetProviders() []string {
	if x != nil {
		return x.Providers
	}
	return nil
}

func (x *SandboxSpec) GetResourceRequirements() *ResourceRequirements {
	if x != nil {
		return x.ResourceRequirements
	}
	return nil
}

func (x *SandboxSpec) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *SandboxSpec) GetTty() bool {
	if x != nil {
		return x.Tty
	}
	return false
}

type SandboxTemplate struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Image            string                 `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	RuntimeClassName string                 `protobuf:"bytes,2,opt,name=runtime_class_name,json=runtimeClassName,proto3" json:"runtime_class_name,omitempty"`
	AgentSocket      string                 `protobuf:"bytes,3,opt,name=agent_socket,json=agentSocket,proto3" json:"agent_socket,omitempty"`
	Labels           map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations      map[string]string      `protobuf:"bytes,5,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Environment      map[string]string      `protobuf:"bytes,6,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Resources        *structpb.Struct       `protobuf:"bytes,7,opt,name=resources,proto3" json:"resources,omitempty"`
	UserNamespaces   *bool                  `protobuf:"varint,10,opt,name=user_namespaces,json=userNamespaces,proto3,oneof" json:"user_namespaces,omitempty"`
	DriverConfig     *structpb.Struct       `protobuf:"bytes,11,opt,name=driver_config,json=driverConfig,proto3" json:"driver_config,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SandboxTemplate) Reset() {
	*x = SandboxTemplate{}
	mi := &file_openshell_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxTemplate) ProtoMessage() {}

func (x *SandboxTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxTemplate.ProtoReflect.Descriptor instead.
func (*SandboxTemplate) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{5}
}

func (x *SandboxTemplate) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SandboxTemplate) GetRuntimeClassName() string {
	if x != nil {
		return x.RuntimeClassName
	}
	return ""
}

func (x *SandboxTemplate) GetAgentSocket() string {
	if x != nil {
		return x.AgentSocket
	}
	return ""
}

func (x *SandboxTemplate) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *SandboxTemplate) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *SandboxTemplate) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *SandboxTemplate) GetResources() *structpb.Struct {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *SandboxTemplate) GetUserNamespaces() bool {
	if x != nil && x.UserNamespaces != nil {
		return *x.UserNamespaces
	}
	return false
}

func (x *SandboxTemplate) GetDriverConfig() *structpb.Struct {
	if x != nil {
		return x.DriverConfig
	}
	return nil
}

type ResourceRequirements struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Gpu           *GpuResourceRequirements `protobuf:"bytes,1,opt,name=gpu,proto3" json:"gpu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceRequirements) Reset() {
	*x = ResourceRequirements{}
	mi := &file_openshell_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceRequirements) ProtoMessage() {}

func (x *ResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceRequirements.ProtoReflect.Descriptor instead.
func (*ResourceRequirements) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{6}
}

func (x *ResourceRequirements) GetGpu() *GpuResourceRequirements {
	if x != nil {
		return x.Gpu
	}
	return nil
}

type GpuResourceRequirements struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         *uint32                `protobuf:"varint,1,opt,name=count,proto3,oneof" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GpuResourceRequirements) Reset() {
	*x = GpuResourceRequirements{}
	mi := &file_openshell_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GpuResourceRequirements) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GpuResourceRequirements) ProtoMessage() {}

func (x *GpuResourceRequirements) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GpuResourceRequirements.ProtoReflect.Descriptor instead.
func (*GpuResourceRequirements) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{7}
}

func (x *GpuResourceRequirements) GetCount() uint32 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

type SandboxPolicy struct {
	state              protoimpl.MessageState              `protogen:"open.v1"`
	Version            uint32                              `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Filesystem         *FilesystemPolicy                   `protobuf:"bytes,2,opt,name=filesystem,proto3" json:"filesystem,omitempty"`
	Landlock           *LandlockPolicy                     `protobuf:"bytes,3,opt,name=landlock,proto3" json:"landlock,omitempty"`
	Process            *ProcessPolicy                      `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	NetworkPolicies    map[string]*NetworkPolicyRule       `protobuf:"bytes,5,rep,name=network_policies,json=networkPolicies,proto3" json:"network_policies,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	NetworkMiddlewares map[string]*NetworkMiddlewareConfig `protobuf:"bytes,6,rep,name=network_middlewares,json=networkMiddlewares,proto3" json:"network_middlewares,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxPolicy) Reset() {
	*x = SandboxPolicy{}
	mi := &file_openshell_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxPolicy) ProtoMessage() {}

func (x *SandboxPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxPolicy.ProtoReflect.Descriptor instead.
func (*SandboxPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{8}
}

func (x *SandboxPolicy) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SandboxPolicy) GetFilesystem() *FilesystemPolicy {
	if x != nil {
		return x.Filesystem
	}
	return nil
}

func (x *SandboxPolicy) GetLandlock() *LandlockPolicy {
	if x != nil {
		return x.Landlock
	}
	return nil
}

func (x *SandboxPolicy) GetProcess() *ProcessPolicy {
	if x != nil {
		return x.Process
	}
	return nil
}

func (x *SandboxPolicy) GetNetworkPolicies() map[string]*NetworkPolicyRule {
	if x != nil {
		return x.NetworkPolicies
	}
	return nil
}

func (x *SandboxPolicy) GetNetworkMiddlewares() map[string]*NetworkMiddlewareConfig {
	if x != nil {
		return x.NetworkMiddlewares
	}
	return nil
}

type FilesystemPolicy struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeWorkdir bool                   `protobuf:"varint,1,opt,name=include_workdir,json=includeWorkdir,proto3" json:"include_workdir,omitempty"`
	ReadOnly       []string               `protobuf:"bytes,2,rep,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	ReadWrite      []string               `protobuf:"bytes,3,rep,name=read_write,json=readWrite,proto3" json:"read_write,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FilesystemPolicy) Reset() {
	*x = FilesystemPolicy{}
	mi := &file_openshell_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilesystemPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilesystemPolicy) ProtoMessage() {}

func (x *FilesystemPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilesystemPolicy.ProtoReflect.Descriptor instead.
func (*FilesystemPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{9}
}

func (x *FilesystemPolicy) GetIncludeWorkdir() bool {
	if x != nil {
		return x.IncludeWorkdir
	}
	return false
}

func (x *FilesystemPolicy) GetReadOnly() []string {
	if x != nil {
		return x.ReadOnly
	}
	return nil
}

func (x *FilesystemPolicy) GetReadWrite() []string {
	if x != nil {
		return x.ReadWrite
	}
	return nil
}

type LandlockPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Compatibility string                 `protobuf:"bytes,1,opt,name=compatibility,proto3" json:"compatibility,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LandlockPolicy) Reset() {
	*x = LandlockPolicy{}
	mi := &file_openshell_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LandlockPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LandlockPolicy) ProtoMessage() {}

func (x *LandlockPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LandlockPolicy.ProtoReflect.Descriptor instead.
func (*LandlockPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{10}
}

func (x *LandlockPolicy) GetCompatibility() string {
	if x != nil {
		return x.Compatibility
	}
	return ""
}

type ProcessPolicy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunAsUser     string                 `protobuf:"bytes,1,opt,name=run_as_user,json=runAsUser,proto3" json:"run_as_user,omitempty"`
	RunAsGroup    string                 `protobuf:"bytes,2,opt,name=run_as_group,json=runAsGroup,proto3" json:"run_as_group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessPolicy) Reset() {
	*x = ProcessPolicy{}
	mi := &file_openshell_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPolicy) ProtoMessage() {}

func (x *ProcessPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPolicy.ProtoReflect.Descriptor instead.
func (*ProcessPolicy) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{11}
}

func (x *ProcessPolicy) GetRunAsUser() string {
	if x != nil {
		return x.RunAsUser
	}
	return ""
}

func (x *ProcessPolicy) GetRunAsGroup() string {
	if x != nil {
		return x.RunAsGroup
	}
	return ""
}

type NetworkPolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Endpoints     []*NetworkEndpoint     `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	Binaries      []*NetworkBinary       `protobuf:"bytes,3,rep,name=binaries,proto3" json:"binaries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkPolicyRule) Reset() {
	*x = NetworkPolicyRule{}
	mi := &file_openshell_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkPolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkPolicyRule) ProtoMessage() {}

func (x *NetworkPolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkPolicyRule.ProtoReflect.Descriptor instead.
func (*NetworkPolicyRule) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkPolicyRule) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkPolicyRule) GetEndpoints() []*NetworkEndpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkPolicyRule) GetBinaries() []*NetworkBinary {
	if x != nil {
		return x.Binaries
	}
	return nil
}

type NetworkMiddlewareConfig struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Name          string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Middleware    string                      `protobuf:"bytes,2,opt,name=middleware,proto3" json:"middleware,omitempty"`
	Config        *structpb.Struct            `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	OnError       string                      `protobuf:"bytes,4,opt,name=on_error,json=onError,proto3" json:"on_error,omitempty"`
	Endpoints     *MiddlewareEndpointSelector `protobuf:"bytes,5,opt,name=endpoints,proto3" json:"endpoints,omitempty"`
	Order         int32                       `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkMiddlewareConfig) Reset() {
	*x = NetworkMiddlewareConfig{}
	mi := &file_openshell_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkMiddlewareConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkMiddlewareConfig) ProtoMessage() {}

func (x *NetworkMiddlewareConfig) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkMiddlewareConfig.ProtoReflect.Descriptor instead.
func (*NetworkMiddlewareConfig) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{13}
}

func (x *NetworkMiddlewareConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetMiddleware() string {
	if x != nil {
		return x.Middleware
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetConfig() *structpb.Struct {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *NetworkMiddlewareConfig) GetOnError() string {
	if x != nil {
		return x.OnError
	}
	return ""
}

func (x *NetworkMiddlewareConfig) GetEndpoints() *MiddlewareEndpointSelector {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *NetworkMiddlewareConfig) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

type MiddlewareEndpointSelector struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Include       []string               `protobuf:"bytes,1,rep,name=include,proto3" json:"include,omitempty"`
	Exclude       []string               `protobuf:"bytes,2,rep,name=exclude,proto3" json:"exclude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MiddlewareEndpointSelector) Reset() {
	*x = MiddlewareEndpointSelector{}
	mi := &file_openshell_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareEndpointSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareEndpointSelector) ProtoMessage() {}

func (x *MiddlewareEndpointSelector) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MiddlewareEndpointSelector.ProtoReflect.Descriptor instead.
func (*MiddlewareEndpointSelector) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{14}
}

func (x *MiddlewareEndpointSelector) GetInclude() []string {
	if x != nil {
		return x.Include
	}
	return nil
}

func (x *MiddlewareEndpointSelector) GetExclude() []string {
	if x != nil {
		return x.Exclude
	}
	return nil
}

type NetworkCredentialBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provider      string                 `protobuf:"bytes,1,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkCredentialBinding) Reset() {
	*x = NetworkCredentialBinding{}
	mi := &file_openshell_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkCredentialBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkCredentialBinding) ProtoMessage() {}

func (x *NetworkCredentialBinding) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkCredentialBinding.ProtoReflect.Descriptor instead.
func (*NetworkCredentialBinding) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{15}
}

func (x *NetworkCredentialBinding) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type NetworkEndpoint struct {
	state                        protoimpl.MessageState       `protogen:"open.v1"`
	Host                         string                       `protobuf:"bytes,1,opt,name=host,proto3" json:"host,omitempty"`
	Port                         uint32                       `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Protocol                     string                       `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Tls                          string                       `protobuf:"bytes,4,opt,name=tls,proto3" json:"tls,omitempty"`
	Enforcement                  string                       `protobuf:"bytes,5,opt,name=enforcement,proto3" json:"enforcement,omitempty"`
	Access                       string                       `protobuf:"bytes,6,opt,name=access,proto3" json:"access,omitempty"`
	Rules                        []*L7Rule                    `protobuf:"bytes,7,rep,name=rules,proto3" json:"rules,omitempty"`
	AllowedIps                   []string                     `protobuf:"bytes,8,rep,name=allowed_ips,json=allowedIps,proto3" json:"allowed_ips,omitempty"`
	Ports                        []uint32                     `protobuf:"varint,9,rep,packed,name=ports,proto3" json:"ports,omitempty"`
	DenyRules                    []*L7DenyRule                `protobuf:"bytes,10,rep,name=deny_rules,json=denyRules,proto3" json:"deny_rules,omitempty"`
	AllowEncodedSlash            bool                         `protobuf:"varint,11,opt,name=allow_encoded_slash,json=allowEncodedSlash,proto3" json:"allow_encoded_slash,omitempty"`
	PersistedQueries             string                       `protobuf:"bytes,12,opt,name=persisted_queries,json=persistedQueries,proto3" json:"persisted_queries,omitempty"`
	GraphqlPersistedQueries      map[string]*GraphqlOperation `protobuf:"bytes,13,rep,name=graphql_persisted_queries,json=graphqlPersistedQueries,proto3" json:"graphql_persisted_queries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	GraphqlMaxBodyBytes          uint32                       `protobuf:"varint,14,opt,name=graphql_max_body_bytes,json=graphqlMaxBodyBytes,proto3" json:"graphql_max_body_bytes,omitempty"`
	Path                         string                       `protobuf:"bytes,15,opt,name=path,proto3" json:"path,omitempty"`
	WebsocketCredentialRewrite   bool                         `protobuf:"varint,16,opt,name=websocket_credential_rewrite,json=websocketCredentialRewrite,proto3" json:"websocket_credential_rewrite,omitempty"`
	RequestBodyCredentialRewrite bool                         `protobuf:"varint,17,opt,name=request_body_credential_rewrite,json=requestBodyCredentialRewrite,proto3" json:"request_body_credential_rewrite,omitempty"`
	AdvisorProposed              bool                         `protobuf:"varint,18,opt,name=advisor_proposed,json=advisorProposed,proto3" json:"advisor_proposed,omitempty"`
	CredentialSigning            string                       `protobuf:"bytes,19,opt,name=credential_signing,json=credentialSigning,proto3" json:"credential_signing,omitempty"`
	SigningService               string                       `protobuf:"bytes,20,opt,name=signing_service,json=signingService,proto3" json:"signing_service,omitempty"`
	SigningRegion                string                       `protobuf:"bytes,21,opt,name=signing_region,json=signingRegion,proto3" json:"signing_region,omitempty"`
	JsonRpcMaxBodyBytes          uint32                       `protobuf:"varint,22,opt,name=json_rpc_max_body_bytes,json=jsonRpcMaxBodyBytes,proto3" json:"json_rpc_max_body_bytes,omitempty"`
	Mcp                          *McpOptions                  `protobuf:"bytes,23,opt,name=mcp,proto3" json:"mcp,omitempty"`
	CredentialBinding            *NetworkCredentialBinding    `protobuf:"bytes,24,opt,name=credential_binding,json=credentialBinding,proto3" json:"credential_binding,omitempty"`
	AllowUninspectedCredentials  bool                         `protobuf:"varint,25,opt,name=allow_uninspected_credentials,json=allowUninspectedCredentials,proto3" json:"allow_uninspected_credentials,omitempty"`
	ProviderCredentialed         bool                         `protobuf:"varint,26,opt,name=provider_credentialed,json=providerCredentialed,proto3" json:"provider_credentialed,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_openshell_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkEndpoint.ProtoReflect.Descriptor instead.
func (*NetworkEndpoint) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{16}
}

func (x *NetworkEndpoint) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *NetworkEndpoint) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *NetworkEndpoint) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *NetworkEndpoint) GetTls() string {
	if x != nil {
		return x.Tls
	}
	return ""
}

func (x *NetworkEndpoint) GetEnforcement() string {
	if x != nil {
		return x.Enforcement
	}
	return ""
}

func (x *NetworkEndpoint) GetAccess() string {
	if x != nil {
		return x.Access
	}
	return ""
}

func (x *NetworkEndpoint) GetRules() []*L7Rule {
	if x != nil {
		return x.Rules
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowedIps() []string {
	if x != nil {
		return x.AllowedIps
	}
	return nil
}

func (x *NetworkEndpoint) GetPorts() []uint32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *NetworkEndpoint) GetDenyRules() []*L7DenyRule {
	if x != nil {
		return x.DenyRules
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowEncodedSlash() bool {
	if x != nil {
		return x.AllowEncodedSlash
	}
	return false
}

func (x *NetworkEndpoint) GetPersistedQueries() string {
	if x != nil {
		return x.PersistedQueries
	}
	return ""
}

func (x *NetworkEndpoint) GetGraphqlPersistedQueries() map[string]*GraphqlOperation {
	if x != nil {
		return x.GraphqlPersistedQueries
	}
	return nil
}

func (x *NetworkEndpoint) GetGraphqlMaxBodyBytes() uint32 {
	if x != nil {
		return x.GraphqlMaxBodyBytes
	}
	return 0
}

func (x *NetworkEndpoint) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *NetworkEndpoint) GetWebsocketCredentialRewrite() bool {
	if x != nil {
		return x.WebsocketCredentialRewrite
	}
	return false
}

func (x *NetworkEndpoint) GetRequestBodyCredentialRewrite() bool {
	if x != nil {
		return x.RequestBodyCredentialRewrite
	}
	return false
}

func (x *NetworkEndpoint) GetAdvisorProposed() bool {
	if x != nil {
		return x.AdvisorProposed
	}
	return false
}

func (x *NetworkEndpoint) GetCredentialSigning() string {
	if x != nil {
		return x.CredentialSigning
	}
	return ""
}

func (x *NetworkEndpoint) GetSigningService() string {
	if x != nil {
		return x.SigningService
	}
	return ""
}

func (x *NetworkEndpoint) GetSigningRegion() string {
	if x != nil {
		return x.SigningRegion
	}
	return ""
}

func (x *NetworkEndpoint) GetJsonRpcMaxBodyBytes() uint32 {
	if x != nil {
		return x.JsonRpcMaxBodyBytes
	}
	return 0
}

func (x *NetworkEndpoint) GetMcp() *McpOptions {
	if x != nil {
		return x.Mcp
	}
	return nil
}

func (x *NetworkEndpoint) GetCredentialBinding() *NetworkCredentialBinding {
	if x != nil {
		return x.CredentialBinding
	}
	return nil
}

func (x *NetworkEndpoint) GetAllowUninspectedCredentials() bool {
	if x != nil {
		return x.AllowUninspectedCredentials
	}
	return false
}

func (x *NetworkEndpoint) GetProviderCredentialed() bool {
	if x != nil {
		return x.ProviderCredentialed
	}
	return false
}

type McpOptions struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	StrictToolNames         *bool                  `protobuf:"varint,1,opt,name=strict_tool_names,json=strictToolNames,proto3,oneof" json:"strict_tool_names,omitempty"`
	AllowAllKnownMcpMethods *bool                  `protobuf:"varint,2,opt,name=allow_all_known_mcp_methods,json=allowAllKnownMcpMethods,proto3,oneof" json:"allow_all_known_mcp_methods,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *McpOptions) Reset() {
	*x = McpOptions{}
	mi := &file_openshell_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpOptions) ProtoMessage() {}

func (x *McpOptions) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpOptions.ProtoReflect.Descriptor instead.
func (*McpOptions) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{17}
}

func (x *McpOptions) GetStrictToolNames() bool {
	if x != nil && x.StrictToolNames != nil {
		return *x.StrictToolNames
	}
	return false
}

func (x *McpOptions) GetAllowAllKnownMcpMethods() bool {
	if x != nil && x.AllowAllKnownMcpMethods != nil {
		return *x.AllowAllKnownMcpMethods
	}
	return false
}

type GraphqlOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationType string                 `protobuf:"bytes,1,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                 `protobuf:"bytes,2,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string               `protobuf:"bytes,3,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphqlOperation) Reset() {
	*x = GraphqlOperation{}
	mi := &file_openshell_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphqlOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphqlOperation) ProtoMessage() {}

func (x *GraphqlOperation) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphqlOperation.ProtoReflect.Descriptor instead.
func (*GraphqlOperation) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{18}
}

func (x *GraphqlOperation) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *GraphqlOperation) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *GraphqlOperation) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

type L7DenyRule struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Method        string                     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                     `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Command       string                     `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Query         map[string]*L7QueryMatcher `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OperationType string                     `protobuf:"bytes,5,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                     `protobuf:"bytes,6,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string                   `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	Params        map[string]*L7QueryMatcher `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7DenyRule) Reset() {
	*x = L7DenyRule{}
	mi := &file_openshell_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7DenyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7DenyRule) ProtoMessage() {}

func (x *L7DenyRule) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7DenyRule.ProtoReflect.Descriptor instead.
func (*L7DenyRule) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{19}
}

func (x *L7DenyRule) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *L7DenyRule) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *L7DenyRule) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *L7DenyRule) GetQuery() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *L7DenyRule) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *L7DenyRule) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *L7DenyRule) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *L7DenyRule) GetParams() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Params
	}
	return nil
}

type L7Rule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allow         *L7Allow               `protobuf:"bytes,1,opt,name=allow,proto3" json:"allow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7Rule) Reset() {
	*x = L7Rule{}
	mi := &file_openshell_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Rule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Rule) ProtoMessage() {}

func (x *L7Rule) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Rule.ProtoReflect.Descriptor instead.
func (*L7Rule) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{20}
}

func (x *L7Rule) GetAllow() *L7Allow {
	if x != nil {
		return x.Allow
	}
	return nil
}

type L7Allow struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Method        string                     `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                     `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	Command       string                     `protobuf:"bytes,3,opt,name=command,proto3" json:"command,omitempty"`
	Query         map[string]*L7QueryMatcher `protobuf:"bytes,4,rep,name=query,proto3" json:"query,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	OperationType string                     `protobuf:"bytes,5,opt,name=operation_type,json=operationType,proto3" json:"operation_type,omitempty"`
	OperationName string                     `protobuf:"bytes,6,opt,name=operation_name,json=operationName,proto3" json:"operation_name,omitempty"`
	Fields        []string                   `protobuf:"bytes,7,rep,name=fields,proto3" json:"fields,omitempty"`
	Params        map[string]*L7QueryMatcher `protobuf:"bytes,9,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7Allow) Reset() {
	*x = L7Allow{}
	mi := &file_openshell_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7Allow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7Allow) ProtoMessage() {}

func (x *L7Allow) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7Allow.ProtoReflect.Descriptor instead.
func (*L7Allow) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{21}
}

func (x *L7Allow) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *L7Allow) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *L7Allow) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *L7Allow) GetQuery() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *L7Allow) GetOperationType() string {
	if x != nil {
		return x.OperationType
	}
	return ""
}

func (x *L7Allow) GetOperationName() string {
	if x != nil {
		return x.OperationName
	}
	return ""
}

func (x *L7Allow) GetFields() []string {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *L7Allow) GetParams() map[string]*L7QueryMatcher {
	if x != nil {
		return x.Params
	}
	return nil
}

type L7QueryMatcher struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Glob          string                 `protobuf:"bytes,1,opt,name=glob,proto3" json:"glob,omitempty"`
	Any           []string               `protobuf:"bytes,2,rep,name=any,proto3" json:"any,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *L7QueryMatcher) Reset() {
	*x = L7QueryMatcher{}
	mi := &file_openshell_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *L7QueryMatcher) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*L7QueryMatcher) ProtoMessage() {}

func (x *L7QueryMatcher) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use L7QueryMatcher.ProtoReflect.Descriptor instead.
func (*L7QueryMatcher) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{22}
}

func (x *L7QueryMatcher) GetGlob() string {
	if x != nil {
		return x.Glob
	}
	return ""
}

func (x *L7QueryMatcher) GetAny() []string {
	if x != nil {
		return x.Any
	}
	return nil
}

type NetworkBinary struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	// Deprecated: Marked as deprecated in openshell.proto.
	Harness       bool `protobuf:"varint,2,opt,name=harness,proto3" json:"harness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkBinary) Reset() {
	*x = NetworkBinary{}
	mi := &file_openshell_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkBinary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkBinary) ProtoMessage() {}

func (x *NetworkBinary) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkBinary.ProtoReflect.Descriptor instead.
func (*NetworkBinary) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{23}
}

func (x *NetworkBinary) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// Deprecated: Marked as deprecated in openshell.proto.
func (x *NetworkBinary) GetHarness() bool {
	if x != nil {
		return x.Harness
	}
	return false
}

type SandboxStatus struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SandboxName           string                 `protobuf:"bytes,1,opt,name=sandbox_name,json=sandboxName,proto3" json:"sandbox_name,omitempty"`
	AgentPod              string                 `protobuf:"bytes,2,opt,name=agent_pod,json=agentPod,proto3" json:"agent_pod,omitempty"`
	AgentFd               string                 `protobuf:"bytes,3,opt,name=agent_fd,json=agentFd,proto3" json:"agent_fd,omitempty"`
	SandboxFd             string                 `protobuf:"bytes,4,opt,name=sandbox_fd,json=sandboxFd,proto3" json:"sandbox_fd,omitempty"`
	Conditions            []*SandboxCondition    `protobuf:"bytes,5,rep,name=conditions,proto3" json:"conditions,omitempty"`
	Phase                 SandboxPhase           `protobuf:"varint,6,opt,name=phase,proto3,enum=openshell.v1.SandboxPhase" json:"phase,omitempty"`
	CurrentPolicyVersion  uint32                 `protobuf:"varint,7,opt,name=current_policy_version,json=currentPolicyVersion,proto3" json:"current_policy_version,omitempty"`
	MainProcessInstanceId string                 `protobuf:"bytes,8,opt,name=main_process_instance_id,json=mainProcessInstanceId,proto3" json:"main_process_instance_id,omitempty"`
	ExitCode              *int32                 `protobuf:"varint,9,opt,name=exit_code,json=exitCode,proto3,oneof" json:"exit_code,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *SandboxStatus) Reset() {
	*x = SandboxStatus{}
	mi := &file_openshell_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxStatus) ProtoMessage() {}

func (x *SandboxStatus) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxStatus.ProtoReflect.Descriptor instead.
func (*SandboxStatus) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{24}
}

func (x *SandboxStatus) GetSandboxName() string {
	if x != nil {
		return x.SandboxName
	}
	return ""
}

func (x *SandboxStatus) GetAgentPod() string {
	if x != nil {
		return x.AgentPod
	}
	return ""
}

func (x *SandboxStatus) GetAgentFd() string {
	if x != nil {
		return x.AgentFd
	}
	return ""
}

func (x *SandboxStatus) GetSandboxFd() string {
	if x != nil {
		return x.SandboxFd
	}
	return ""
}

func (x *SandboxStatus) GetConditions() []*SandboxCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

func (x *SandboxStatus) GetPhase() SandboxPhase {
	if x != nil {
		return x.Phase
	}
	return SandboxPhase_SANDBOX_PHASE_UNSPECIFIED
}

func (x *SandboxStatus) GetCurrentPolicyVersion() uint32 {
	if x != nil {
		return x.CurrentPolicyVersion
	}
	return 0
}

func (x *SandboxStatus) GetMainProcessInstanceId() string {
	if x != nil {
		return x.MainProcessInstanceId
	}
	return ""
}

func (x *SandboxStatus) GetExitCode() int32 {
	if x != nil && x.ExitCode != nil {
		return *x.ExitCode
	}
	return 0
}

type SandboxCondition struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Type               string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Status             string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason             string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	LastTransitionTime string                 `protobuf:"bytes,5,opt,name=last_transition_time,json=lastTransitionTime,proto3" json:"last_transition_time,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SandboxCondition) Reset() {
	*x = SandboxCondition{}
	mi := &file_openshell_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxCondition) ProtoMessage() {}

func (x *SandboxCondition) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxCondition.ProtoReflect.Descriptor instead.
func (*SandboxCondition) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{25}
}

func (x *SandboxCondition) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SandboxCondition) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SandboxCondition) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SandboxCondition) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SandboxCondition) GetLastTransitionTime() string {
	if x != nil {
		return x.LastTransitionTime
	}
	return ""
}

type CreateSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *SandboxSpec           `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Annotations   map[string]string      `protobuf:"bytes,4,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Workspace     string                 `protobuf:"bytes,5,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	mi := &file_openshell_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSandboxRequest.ProtoReflect.Descriptor instead.
func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{26}
}

func (x *CreateSandboxRequest) GetSpec() *SandboxSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *CreateSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSandboxRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *CreateSandboxRequest) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *CreateSandboxRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type GetSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	mi := &file_openshell_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSandboxRequest.ProtoReflect.Descriptor instead.
func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{27}
}

func (x *GetSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetSandboxRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type DeleteSandboxRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Workspace     string                 `protobuf:"bytes,2,opt,name=workspace,proto3" json:"workspace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxRequest) Reset() {
	*x = DeleteSandboxRequest{}
	mi := &file_openshell_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxRequest) ProtoMessage() {}

func (x *DeleteSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxRequest.ProtoReflect.Descriptor instead.
func (*DeleteSandboxRequest) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteSandboxRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteSandboxRequest) GetWorkspace() string {
	if x != nil {
		return x.Workspace
	}
	return ""
}

type SandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sandbox       *Sandbox               `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SandboxResponse) Reset() {
	*x = SandboxResponse{}
	mi := &file_openshell_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxResponse) ProtoMessage() {}

func (x *SandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SandboxResponse.ProtoReflect.Descriptor instead.
func (*SandboxResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{29}
}

func (x *SandboxResponse) GetSandbox() *Sandbox {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

type DeleteSandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSandboxResponse) Reset() {
	*x = DeleteSandboxResponse{}
	mi := &file_openshell_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSandboxResponse) ProtoMessage() {}

func (x *DeleteSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSandboxResponse.ProtoReflect.Descriptor instead.
func (*DeleteSandboxResponse) Descriptor() ([]byte, []int) {
	return file_openshell_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteSandboxResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

var File_openshell_proto protoreflect.FileDescriptor

const file_openshell_proto_rawDesc = "" +
	"\n" +
	"\x0fopenshell.proto\x12\fopenshell.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x0f\n" +
	"\rHealthRequest\"_\n" +
	"\x0eHealthResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.openshell.v1.ServiceStatusR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"\xd7\x03\n" +
	"\n" +
	"ObjectMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\x12<\n" +
	"\x06labels\x18\x04 \x03(\v2$.openshell.v1.ObjectMeta.LabelsEntryR\x06labels\x12)\n" +
	"\x10resource_version\x18\x05 \x01(\x04R\x0fresourceVersion\x12K\n" +
	"\vannotations\x18\x06 \x03(\v2).openshell.v1.ObjectMeta.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\tworkspace\x18\a \x01(\tR\tworkspace\x122\n" +
	"\x15deletion_timestamp_ms\x18\b \x01(\x03R\x13deletionTimestampMs\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa3\x01\n" +
	"\aSandbox\x124\n" +
	"\bmetadata\x18\x01 \x01(\v2\x18.openshell.v1.ObjectMetaR\bmetadata\x12-\n" +
	"\x04spec\x18\x02 \x01(\v2\x19.openshell.v1.SandboxSpecR\x04spec\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x1b.openshell.v1.SandboxStatusR\x06status\"\xcb\x03\n" +
	"\vSandboxSpec\x12\x1b\n" +
	"\tlog_level\x18\x01 \x01(\tR\blogLevel\x12L\n" +
	"\venvironment\x18\x05 \x03(\v2*.openshell.v1.SandboxSpec.EnvironmentEntryR\venvironment\x129\n" +
	"\btemplate\x18\x06 \x01(\v2\x1d.openshell.v1.SandboxTemplateR\btemplate\x123\n" +
	"\x06policy\x18\a \x01(\v2\x1b.openshell.v1.SandboxPolicyR\x06policy\x12\x1c\n" +
	"\tproviders\x18\b \x03(\tR\tproviders\x12W\n" +
	"\x15resource_requirements\x18\t \x01(\v2\".openshell.v1.ResourceRequirementsR\x14resourceRequirements\x12\x18\n" +
	"\acommand\x18\f \x03(\tR\acommand\x12\x10\n" +
	"\x03tty\x18\r \x01(\bR\x03tty\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x05\n" +
	"\x0fSandboxTemplate\x12\x14\n" +
	"\x05image\x18\x01 \x01(\tR\x05image\x12,\n" +
	"\x12runtime_class_name\x18\x02 \x01(\tR\x10runtimeClassName\x12!\n" +
	"\fagent_socket\x18\x03 \x01(\tR\vagentSocket\x12A\n" +
	"\x06labels\x18\x04 \x03(\v2).openshell.v1.SandboxTemplate.LabelsEntryR\x06labels\x12P\n" +
	"\vannotations\x18\x05 \x03(\v2..openshell.v1.SandboxTemplate.AnnotationsEntryR\vannotations\x12P\n" +
	"\venvironment\x18\x06 \x03(\v2..openshell.v1.SandboxTemplate.EnvironmentEntryR\venvironment\x125\n" +
	"\tresources\x18\a \x01(\v2\x17.google.protobuf.StructR\tresources\x12,\n" +
	"\x0fuser_namespaces\x18\n" +
	" \x01(\bH\x00R\x0euserNamespaces\x88\x01\x01\x12<\n" +
	"\rdriver_config\x18\v \x01(\v2\x17.google.protobuf.StructR\fdriverConfig\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x12\n" +
	"\x10_user_namespaces\"O\n" +
	"\x14ResourceRequirements\x127\n" +
	"\x03gpu\x18\x01 \x01(\v2%.openshell.v1.GpuResourceRequirementsR\x03gpu\">\n" +
	"\x17GpuResourceRequirements\x12\x19\n" +
	"\x05count\x18\x01 \x01(\rH\x00R\x05count\x88\x01\x01B\b\n" +
	"\x06_count\"\xf0\x04\n" +
	"\rSandboxPolicy\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12>\n" +
	"\n" +
	"filesystem\x18\x02 \x01(\v2\x1e.openshell.v1.FilesystemPolicyR\n" +
	"filesystem\x128\n" +
	"\blandlock\x18\x03 \x01(\v2\x1c.openshell.v1.LandlockPolicyR\blandlock\x125\n" +
	"\aprocess\x18\x04 \x01(\v2\x1b.openshell.v1.ProcessPolicyR\aprocess\x12[\n" +
	"\x10network_policies\x18\x05 \x03(\v20.openshell.v1.SandboxPolicy.NetworkPoliciesEntryR\x0fnetworkPolicies\x12d\n" +
	"\x13network_middlewares\x18\x06 \x03(\v23.openshell.v1.SandboxPolicy.NetworkMiddlewaresEntryR\x12networkMiddlewares\x1ac\n" +
	"\x14NetworkPoliciesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x125\n" +
	"\x05value\x18\x02 \x01(\v2\x1f.openshell.v1.NetworkPolicyRuleR\x05value:\x028\x01\x1al\n" +
	"\x17NetworkMiddlewaresEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.openshell.v1.NetworkMiddlewareConfigR\x05value:\x028\x01\"w\n" +
	"\x10FilesystemPolicy\x12'\n" +
	"\x0finclude_workdir\x18\x01 \x01(\bR\x0eincludeWorkdir\x12\x1b\n" +
	"\tread_only\x18\x02 \x03(\tR\breadOnly\x12\x1d\n" +
	"\n" +
	"read_write\x18\x03 \x03(\tR\treadWrite\"6\n" +
	"\x0eLandlockPolicy\x12$\n" +
	"\rcompatibility\x18\x01 \x01(\tR\rcompatibility\"Q\n" +
	"\rProcessPolicy\x12\x1e\n" +
	"\vrun_as_user\x18\x01 \x01(\tR\trunAsUser\x12 \n" +
	"\frun_as_group\x18\x02 \x01(\tR\n" +
	"runAsGroup\"\x9d\x01\n" +
	"\x11NetworkPolicyRule\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\tendpoints\x18\x02 \x03(\v2\x1d.openshell.v1.NetworkEndpointR\tendpoints\x127\n" +
	"\bbinaries\x18\x03 \x03(\v2\x1b.openshell.v1.NetworkBinaryR\bbinaries\"\xf7\x01\n" +
	"\x17NetworkMiddlewareConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"middleware\x18\x02 \x01(\tR\n" +
	"middleware\x12/\n" +
	"\x06config\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06config\x12\x19\n" +
	"\bon_error\x18\x04 \x01(\tR\aonError\x12F\n" +
	"\tendpoints\x18\x05 \x01(\v2(.openshell.v1.MiddlewareEndpointSelectorR\tendpoints\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\"P\n" +
	"\x1aMiddlewareEndpointSelector\x12\x18\n" +
	"\ainclude\x18\x01 \x03(\tR\ainclude\x12\x18\n" +
	"\aexclude\x18\x02 \x03(\tR\aexclude\"6\n" +
	"\x18NetworkCredentialBinding\x12\x1a\n" +
	"\bprovider\x18\x01 \x01(\tR\bprovider\"\xac\n" +
	"\n" +
	"\x0fNetworkEndpoint\x12\x12\n" +
	"\x04host\x18\x01 \x01(\tR\x04host\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x10\n" +
	"\x03tls\x18\x04 \x01(\tR\x03tls\x12 \n" +
	"\venforcement\x18\x05 \x01(\tR\venforcement\x12\x16\n" +
	"\x06access\x18\x06 \x01(\tR\x06access\x12*\n" +
	"\x05rules\x18\a \x03(\v2\x14.openshell.v1.L7RuleR\x05rules\x12\x1f\n" +
	"\vallowed_ips\x18\b \x03(\tR\n" +
	"allowedIps\x12\x14\n" +
	"\x05ports\x18\t \x03(\rR\x05ports\x127\n" +
	"\n" +
	"deny_rules\x18\n" +
	" \x03(\v2\x18.openshell.v1.L7DenyRuleR\tdenyRules\x12.\n" +
	"\x13allow_encoded_slash\x18\v \x01(\bR\x11allowEncodedSlash\x12+\n" +
	"\x11persisted_queries\x18\f \x01(\tR\x10persistedQueries\x12v\n" +
	"\x19graphql_persisted_queries\x18\r \x03(\v2:.openshell.v1.NetworkEndpoint.GraphqlPersistedQueriesEntryR\x17graphqlPersistedQueries\x123\n" +
	"\x16graphql_max_body_bytes\x18\x0e \x01(\rR\x13graphqlMaxBodyBytes\x12\x12\n" +
	"\x04path\x18\x0f \x01(\tR\x04path\x12@\n" +
	"\x1cwebsocket_credential_rewrite\x18\x10 \x01(\bR\x1awebsocketCredentialRewrite\x12E\n" +
	"\x1frequest_body_credential_rewrite\x18\x11 \x01(\bR\x1crequestBodyCredentialRewrite\x12)\n" +
	"\x10advisor_proposed\x18\x12 \x01(\bR\x0fadvisorProposed\x12-\n" +
	"\x12credential_signing\x18\x13 \x01(\tR\x11credentialSigning\x12'\n" +
	"\x0fsigning_service\x18\x14 \x01(\tR\x0esigningService\x12%\n" +
	"\x0esigning_region\x18\x15 \x01(\tR\rsigningRegion\x124\n" +
	"\x17json_rpc_max_body_bytes\x18\x16 \x01(\rR\x13jsonRpcMaxBodyBytes\x12*\n" +
	"\x03mcp\x18\x17 \x01(\v2\x18.openshell.v1.McpOptionsR\x03mcp\x12U\n" +
	"\x12credential_binding\x18\x18 \x01(\v2&.openshell.v1.NetworkCredentialBindingR\x11credentialBinding\x12B\n" +
	"\x1dallow_uninspected_credentials\x18\x19 \x01(\bR\x1ballowUninspectedCredentials\x123\n" +
	"\x15provider_credentialed\x18\x1a \x01(\bR\x14providerCredentialed\x1aj\n" +
	"\x1cGraphqlPersistedQueriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x124\n" +
	"\x05value\x18\x02 \x01(\v2\x1e.openshell.v1.GraphqlOperationR\x05value:\x028\x01\"\xb6\x01\n" +
	"\n" +
	"McpOptions\x12/\n" +
	"\x11strict_tool_names\x18\x01 \x01(\bH\x00R\x0fstrictToolNames\x88\x01\x01\x12A\n" +
	"\x1ballow_all_known_mcp_methods\x18\x02 \x01(\bH\x01R\x17allowAllKnownMcpMethods\x88\x01\x01B\x14\n" +
	"\x12_strict_tool_namesB\x1e\n" +
	"\x1c_allow_all_known_mcp_methods\"x\n" +
	"\x10GraphqlOperation\x12%\n" +
	"\x0eoperation_type\x18\x01 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x02 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\x03 \x03(\tR\x06fields\"\xe8\x03\n" +
	"\n" +
	"L7DenyRule\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x129\n" +
	"\x05query\x18\x04 \x03(\v2#.openshell.v1.L7DenyRule.QueryEntryR\x05query\x12%\n" +
	"\x0eoperation_type\x18\x05 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x06 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x12<\n" +
	"\x06params\x18\t \x03(\v2$.openshell.v1.L7DenyRule.ParamsEntryR\x06params\x1aV\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openshell.v1.L7QueryMatcherR\x05value:\x028\x01\x1aW\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openshell.v1.L7QueryMatcherR\x05value:\x028\x01J\x04\b\b\x10\t\"5\n" +
	"\x06L7Rule\x12+\n" +
	"\x05allow\x18\x01 \x01(\v2\x15.openshell.v1.L7AllowR\x05allow\"\xdf\x03\n" +
	"\aL7Allow\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x18\n" +
	"\acommand\x18\x03 \x01(\tR\acommand\x126\n" +
	"\x05query\x18\x04 \x03(\v2 .openshell.v1.L7Allow.QueryEntryR\x05query\x12%\n" +
	"\x0eoperation_type\x18\x05 \x01(\tR\roperationType\x12%\n" +
	"\x0eoperation_name\x18\x06 \x01(\tR\roperationName\x12\x16\n" +
	"\x06fields\x18\a \x03(\tR\x06fields\x129\n" +
	"\x06params\x18\t \x03(\v2!.openshell.v1.L7Allow.ParamsEntryR\x06params\x1aV\n" +
	"\n" +
	"QueryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openshell.v1.L7QueryMatcherR\x05value:\x028\x01\x1aW\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x122\n" +
	"\x05value\x18\x02 \x01(\v2\x1c.openshell.v1.L7QueryMatcherR\x05value:\x028\x01J\x04\b\b\x10\t\"6\n" +
	"\x0eL7QueryMatcher\x12\x12\n" +
	"\x04glob\x18\x01 \x01(\tR\x04glob\x12\x10\n" +
	"\x03any\x18\x02 \x03(\tR\x03any\"A\n" +
	"\rNetworkBinary\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x1c\n" +
	"\aharness\x18\x02 \x01(\bB\x02\x18\x01R\aharness\"\x9a\x03\n" +
	"\rSandboxStatus\x12!\n" +
	"\fsandbox_name\x18\x01 \x01(\tR\vsandboxName\x12\x1b\n" +
	"\tagent_pod\x18\x02 \x01(\tR\bagentPod\x12\x19\n" +
	"\bagent_fd\x18\x03 \x01(\tR\aagentFd\x12\x1d\n" +
	"\n" +
	"sandbox_fd\x18\x04 \x01(\tR\tsandboxFd\x12>\n" +
	"\n" +
	"conditions\x18\x05 \x03(\v2\x1e.openshell.v1.SandboxConditionR\n" +
	"conditions\x120\n" +
	"\x05phase\x18\x06 \x01(\x0e2\x1a.openshell.v1.SandboxPhaseR\x05phase\x124\n" +
	"\x16current_policy_version\x18\a \x01(\rR\x14currentPolicyVersion\x127\n" +
	"\x18main_process_instance_id\x18\b \x01(\tR\x15mainProcessInstanceId\x12 \n" +
	"\texit_code\x18\t \x01(\x05H\x00R\bexitCode\x88\x01\x01B\f\n" +
	"\n" +
	"_exit_code\"\xa2\x01\n" +
	"\x10SandboxCondition\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x120\n" +
	"\x14last_transition_time\x18\x05 \x01(\tR\x12lastTransitionTime\"\x91\x03\n" +
	"\x14CreateSandboxRequest\x12-\n" +
	"\x04spec\x18\x01 \x01(\v2\x19.openshell.v1.SandboxSpecR\x04spec\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12F\n" +
	"\x06labels\x18\x03 \x03(\v2..openshell.v1.CreateSandboxRequest.LabelsEntryR\x06labels\x12U\n" +
	"\vannotations\x18\x04 \x03(\v23.openshell.v1.CreateSandboxRequest.AnnotationsEntryR\vannotations\x12\x1c\n" +
	"\tworkspace\x18\x05 \x01(\tR\tworkspace\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AnnotationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"E\n" +
	"\x11GetSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"H\n" +
	"\x14DeleteSandboxRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tworkspace\x18\x02 \x01(\tR\tworkspace\"B\n" +
	"\x0fSandboxResponse\x12/\n" +
	"\asandbox\x18\x01 \x01(\v2\x15.openshell.v1.SandboxR\asandbox\"1\n" +
	"\x15DeleteSandboxResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted*\x86\x01\n" +
	"\rServiceStatus\x12\x1e\n" +
	"\x1aSERVICE_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SERVICE_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17SERVICE_STATUS_DEGRADED\x10\x02\x12\x1c\n" +
	"\x18SERVICE_STATUS_UNHEALTHY\x10\x03*\x89\x02\n" +
	"\fSandboxPhase\x12\x1d\n" +
	"\x19SANDBOX_PHASE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aSANDBOX_PHASE_PROVISIONING\x10\x01\x12\x17\n" +
	"\x13SANDBOX_PHASE_READY\x10\x02\x12\x17\n" +
	"\x13SANDBOX_PHASE_ERROR\x10\x03\x12\x1a\n" +
	"\x16SANDBOX_PHASE_DELETING\x10\x04\x12\x19\n" +
	"\x15SANDBOX_PHASE_UNKNOWN\x10\x05\x12\x1a\n" +
	"\x16SANDBOX_PHASE_STOPPING\x10\x06\x12\x19\n" +
	"\x15SANDBOX_PHASE_STOPPED\x10\a\x12\x1a\n" +
	"\x16SANDBOX_PHASE_STARTING\x10\b2\xcc\x02\n" +
	"\tOpenShell\x12C\n" +
	"\x06Health\x12\x1b.openshell.v1.HealthRequest\x1a\x1c.openshell.v1.HealthResponse\x12R\n" +
	"\rCreateSandbox\x12\".openshell.v1.CreateSandboxRequest\x1a\x1d.openshell.v1.SandboxResponse\x12L\n" +
	"\n" +
	"GetSandbox\x12\x1f.openshell.v1.GetSandboxRequest\x1a\x1d.openshell.v1.SandboxResponse\x12X\n" +
	"\rDeleteSandbox\x12\".openshell.v1.DeleteSandboxRequest\x1a#.openshell.v1.DeleteSandboxResponseBRZPgithub.com/openclaw/openclaw-enterprise/components/runtime-security/openshell/pbb\x06proto3"

var (
	file_openshell_proto_rawDescOnce sync.Once
	file_openshell_proto_rawDescData []byte
)

func file_openshell_proto_rawDescGZIP() []byte {
	file_openshell_proto_rawDescOnce.Do(func() {
		file_openshell_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_proto_rawDesc), len(file_openshell_proto_rawDesc)))
	})
	return file_openshell_proto_rawDescData
}

var file_openshell_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_openshell_proto_msgTypes = make([]protoimpl.MessageInfo, 46)
var file_openshell_proto_goTypes = []any{
	(ServiceStatus)(0),                 // 0: openshell.v1.ServiceStatus
	(SandboxPhase)(0),                  // 1: openshell.v1.SandboxPhase
	(*HealthRequest)(nil),              // 2: openshell.v1.HealthRequest
	(*HealthResponse)(nil),             // 3: openshell.v1.HealthResponse
	(*ObjectMeta)(nil),                 // 4: openshell.v1.ObjectMeta
	(*Sandbox)(nil),                    // 5: openshell.v1.Sandbox
	(*SandboxSpec)(nil),                // 6: openshell.v1.SandboxSpec
	(*SandboxTemplate)(nil),            // 7: openshell.v1.SandboxTemplate
	(*ResourceRequirements)(nil),       // 8: openshell.v1.ResourceRequirements
	(*GpuResourceRequirements)(nil),    // 9: openshell.v1.GpuResourceRequirements
	(*SandboxPolicy)(nil),              // 10: openshell.v1.SandboxPolicy
	(*FilesystemPolicy)(nil),           // 11: openshell.v1.FilesystemPolicy
	(*LandlockPolicy)(nil),             // 12: openshell.v1.LandlockPolicy
	(*ProcessPolicy)(nil),              // 13: openshell.v1.ProcessPolicy
	(*NetworkPolicyRule)(nil),          // 14: openshell.v1.NetworkPolicyRule
	(*NetworkMiddlewareConfig)(nil),    // 15: openshell.v1.NetworkMiddlewareConfig
	(*MiddlewareEndpointSelector)(nil), // 16: openshell.v1.MiddlewareEndpointSelector
	(*NetworkCredentialBinding)(nil),   // 17: openshell.v1.NetworkCredentialBinding
	(*NetworkEndpoint)(nil),            // 18: openshell.v1.NetworkEndpoint
	(*McpOptions)(nil),                 // 19: openshell.v1.McpOptions
	(*GraphqlOperation)(nil),           // 20: openshell.v1.GraphqlOperation
	(*L7DenyRule)(nil),                 // 21: openshell.v1.L7DenyRule
	(*L7Rule)(nil),                     // 22: openshell.v1.L7Rule
	(*L7Allow)(nil),                    // 23: openshell.v1.L7Allow
	(*L7QueryMatcher)(nil),             // 24: openshell.v1.L7QueryMatcher
	(*NetworkBinary)(nil),              // 25: openshell.v1.NetworkBinary
	(*SandboxStatus)(nil),              // 26: openshell.v1.SandboxStatus
	(*SandboxCondition)(nil),           // 27: openshell.v1.SandboxCondition
	(*CreateSandboxRequest)(nil),       // 28: openshell.v1.CreateSandboxRequest
	(*GetSandboxRequest)(nil),          // 29: openshell.v1.GetSandboxRequest
	(*DeleteSandboxRequest)(nil),       // 30: openshell.v1.DeleteSandboxRequest
	(*SandboxResponse)(nil),            // 31: openshell.v1.SandboxResponse
	(*DeleteSandboxResponse)(nil),      // 32: openshell.v1.DeleteSandboxResponse
	nil,                                // 33: openshell.v1.ObjectMeta.LabelsEntry
	nil,                                // 34: openshell.v1.ObjectMeta.AnnotationsEntry
	nil,                                // 35: openshell.v1.SandboxSpec.EnvironmentEntry
	nil,                                // 36: openshell.v1.SandboxTemplate.LabelsEntry
	nil,                                // 37: openshell.v1.SandboxTemplate.AnnotationsEntry
	nil,                                // 38: openshell.v1.SandboxTemplate.EnvironmentEntry
	nil,                                // 39: openshell.v1.SandboxPolicy.NetworkPoliciesEntry
	nil,                                // 40: openshell.v1.SandboxPolicy.NetworkMiddlewaresEntry
	nil,                                // 41: openshell.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry
	nil,                                // 42: openshell.v1.L7DenyRule.QueryEntry
	nil,                                // 43: openshell.v1.L7DenyRule.ParamsEntry
	nil,                                // 44: openshell.v1.L7Allow.QueryEntry
	nil,                                // 45: openshell.v1.L7Allow.ParamsEntry
	nil,                                // 46: openshell.v1.CreateSandboxRequest.LabelsEntry
	nil,                                // 47: openshell.v1.CreateSandboxRequest.AnnotationsEntry
	(*structpb.Struct)(nil),            // 48: google.protobuf.Struct
}
var file_openshell_proto_depIdxs = []int32{
	0,  // 0: openshell.v1.HealthResponse.status:type_name -> openshell.v1.ServiceStatus
	33, // 1: openshell.v1.ObjectMeta.labels:type_name -> openshell.v1.ObjectMeta.LabelsEntry
	34, // 2: openshell.v1.ObjectMeta.annotations:type_name -> openshell.v1.ObjectMeta.AnnotationsEntry
	4,  // 3: openshell.v1.Sandbox.metadata:type_name -> openshell.v1.ObjectMeta
	6,  // 4: openshell.v1.Sandbox.spec:type_name -> openshell.v1.SandboxSpec
	26, // 5: openshell.v1.Sandbox.status:type_name -> openshell.v1.SandboxStatus
	35, // 6: openshell.v1.SandboxSpec.environment:type_name -> openshell.v1.SandboxSpec.EnvironmentEntry
	7,  // 7: openshell.v1.SandboxSpec.template:type_name -> openshell.v1.SandboxTemplate
	10, // 8: openshell.v1.SandboxSpec.policy:type_name -> openshell.v1.SandboxPolicy
	8,  // 9: openshell.v1.SandboxSpec.resource_requirements:type_name -> openshell.v1.ResourceRequirements
	36, // 10: openshell.v1.SandboxTemplate.labels:type_name -> openshell.v1.SandboxTemplate.LabelsEntry
	37, // 11: openshell.v1.SandboxTemplate.annotations:type_name -> openshell.v1.SandboxTemplate.AnnotationsEntry
	38, // 12: openshell.v1.SandboxTemplate.environment:type_name -> openshell.v1.SandboxTemplate.EnvironmentEntry
	48, // 13: openshell.v1.SandboxTemplate.resources:type_name -> google.protobuf.Struct
	48, // 14: openshell.v1.SandboxTemplate.driver_config:type_name -> google.protobuf.Struct
	9,  // 15: openshell.v1.ResourceRequirements.gpu:type_name -> openshell.v1.GpuResourceRequirements
	11, // 16: openshell.v1.SandboxPolicy.filesystem:type_name -> openshell.v1.FilesystemPolicy
	12, // 17: openshell.v1.SandboxPolicy.landlock:type_name -> openshell.v1.LandlockPolicy
	13, // 18: openshell.v1.SandboxPolicy.process:type_name -> openshell.v1.ProcessPolicy
	39, // 19: openshell.v1.SandboxPolicy.network_policies:type_name -> openshell.v1.SandboxPolicy.NetworkPoliciesEntry
	40, // 20: openshell.v1.SandboxPolicy.network_middlewares:type_name -> openshell.v1.SandboxPolicy.NetworkMiddlewaresEntry
	18, // 21: openshell.v1.NetworkPolicyRule.endpoints:type_name -> openshell.v1.NetworkEndpoint
	25, // 22: openshell.v1.NetworkPolicyRule.binaries:type_name -> openshell.v1.NetworkBinary
	48, // 23: openshell.v1.NetworkMiddlewareConfig.config:type_name -> google.protobuf.Struct
	16, // 24: openshell.v1.NetworkMiddlewareConfig.endpoints:type_name -> openshell.v1.MiddlewareEndpointSelector
	22, // 25: openshell.v1.NetworkEndpoint.rules:type_name -> openshell.v1.L7Rule
	21, // 26: openshell.v1.NetworkEndpoint.deny_rules:type_name -> openshell.v1.L7DenyRule
	41, // 27: openshell.v1.NetworkEndpoint.graphql_persisted_queries:type_name -> openshell.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry
	19, // 28: openshell.v1.NetworkEndpoint.mcp:type_name -> openshell.v1.McpOptions
	17, // 29: openshell.v1.NetworkEndpoint.credential_binding:type_name -> openshell.v1.NetworkCredentialBinding
	42, // 30: openshell.v1.L7DenyRule.query:type_name -> openshell.v1.L7DenyRule.QueryEntry
	43, // 31: openshell.v1.L7DenyRule.params:type_name -> openshell.v1.L7DenyRule.ParamsEntry
	23, // 32: openshell.v1.L7Rule.allow:type_name -> openshell.v1.L7Allow
	44, // 33: openshell.v1.L7Allow.query:type_name -> openshell.v1.L7Allow.QueryEntry
	45, // 34: openshell.v1.L7Allow.params:type_name -> openshell.v1.L7Allow.ParamsEntry
	27, // 35: openshell.v1.SandboxStatus.conditions:type_name -> openshell.v1.SandboxCondition
	1,  // 36: openshell.v1.SandboxStatus.phase:type_name -> openshell.v1.SandboxPhase
	6,  // 37: openshell.v1.CreateSandboxRequest.spec:type_name -> openshell.v1.SandboxSpec
	46, // 38: openshell.v1.CreateSandboxRequest.labels:type_name -> openshell.v1.CreateSandboxRequest.LabelsEntry
	47, // 39: openshell.v1.CreateSandboxRequest.annotations:type_name -> openshell.v1.CreateSandboxRequest.AnnotationsEntry
	5,  // 40: openshell.v1.SandboxResponse.sandbox:type_name -> openshell.v1.Sandbox
	14, // 41: openshell.v1.SandboxPolicy.NetworkPoliciesEntry.value:type_name -> openshell.v1.NetworkPolicyRule
	15, // 42: openshell.v1.SandboxPolicy.NetworkMiddlewaresEntry.value:type_name -> openshell.v1.NetworkMiddlewareConfig
	20, // 43: openshell.v1.NetworkEndpoint.GraphqlPersistedQueriesEntry.value:type_name -> openshell.v1.GraphqlOperation
	24, // 44: openshell.v1.L7DenyRule.QueryEntry.value:type_name -> openshell.v1.L7QueryMatcher
	24, // 45: openshell.v1.L7DenyRule.ParamsEntry.value:type_name -> openshell.v1.L7QueryMatcher
	24, // 46: openshell.v1.L7Allow.QueryEntry.value:type_name -> openshell.v1.L7QueryMatcher
	24, // 47: openshell.v1.L7Allow.ParamsEntry.value:type_name -> openshell.v1.L7QueryMatcher
	2,  // 48: openshell.v1.OpenShell.Health:input_type -> openshell.v1.HealthRequest
	28, // 49: openshell.v1.OpenShell.CreateSandbox:input_type -> openshell.v1.CreateSandboxRequest
	29, // 50: openshell.v1.OpenShell.GetSandbox:input_type -> openshell.v1.GetSandboxRequest
	30, // 51: openshell.v1.OpenShell.DeleteSandbox:input_type -> openshell.v1.DeleteSandboxRequest
	3,  // 52: openshell.v1.OpenShell.Health:output_type -> openshell.v1.HealthResponse
	31, // 53: openshell.v1.OpenShell.CreateSandbox:output_type -> openshell.v1.SandboxResponse
	31, // 54: openshell.v1.OpenShell.GetSandbox:output_type -> openshell.v1.SandboxResponse
	32, // 55: openshell.v1.OpenShell.DeleteSandbox:output_type -> openshell.v1.DeleteSandboxResponse
	52, // [52:56] is the sub-list for method output_type
	48, // [48:52] is the sub-list for method input_type
	48, // [48:48] is the sub-list for extension type_name
	48, // [48:48] is the sub-list for extension extendee
	0,  // [0:48] is the sub-list for field type_name
}

func init() { file_openshell_proto_init() }
func file_openshell_proto_init() {
	if File_openshell_proto != nil {
		return
	}
	file_openshell_proto_msgTypes[5].OneofWrappers = []any{}
	file_openshell_proto_msgTypes[7].OneofWrappers = []any{}
	file_openshell_proto_msgTypes[17].OneofWrappers = []any{}
	file_openshell_proto_msgTypes[24].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_proto_rawDesc), len(file_openshell_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   46,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openshell_proto_goTypes,
		DependencyIndexes: file_openshell_proto_depIdxs,
		EnumInfos:         file_openshell_proto_enumTypes,
		MessageInfos:      file_openshell_proto_msgTypes,
	}.Build()
	File_openshell_proto = out.File
	file_openshell_proto_goTypes = nil
	file_openshell_proto_depIdxs = nil
}
